
services:
  db:
    image: postgres
    environment: 
      POSTGRES_USER: 'admin'
      POSTGRES_PASSWORD: 'password'
      POSTGRES_DB: RAD2021_s3707189_s3717497_development
    # the post only exposed to web service internally
    # ports:
    #   - "5432:5432"
    volumes:
      - postgres:/data/postgres
  web:
    build: .
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_HOST: db
      DATABASE_USERNAME: "admin"
      DATABASE_PASSWORD: "password"
      DATABASE_PORT: 5432
    volumes:
      - .:/myapp:delegated
      - bundle:/usr/local/bundle
      - cache:/myapp/tmp/cache
volumes:
  postgres:
  cache:
  bundle:
